# Configuration docker pour déployer un noeud elasticsearch de theses.fr
version: "3.5"

services:

  ###################################################################
  # Configuration pour ajouter un noeud dans le cluster elasticsearch
  # de theses.fr / Voir la configuration dans .env-dist
  theses-elasticsearch:
    container_name: theses-elasticsearch-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}
    image: docker.elastic.co/elasticsearch/elasticsearch:${THESES_ELASTICSEARCH_VERSION}
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    volumes:
      - ./volumes/theses-elasticsearch-setupcerts/:/usr/share/elasticsearch/config/certs/
      - ./volumes/theses-elasticsearch/:/usr/share/elasticsearch/data/
      - ./volumes/theses-elasticsearch-tmp/:/usr/share/elasticsearch/tmp/
      - ./volumes/theses-elasticsearch-backup/:${THESES_ELASTICSEARCH_SNAPSHOTS_DIR}
    ports:
      # réglage explicites des ports internes et externes pour pouvoir fonctionner en cluster
      # cf https://blog.cri.epita.fr/post/2019-06-10-elasticsearch-cluster-formation-issue/
      - ${THESES_ELASTICSEARCH_HTTP_PORT}:${THESES_ELASTICSEARCH_HTTP_PORT}
      - ${THESES_ELASTICSEARCH_TRANSPORT_PORT}:${THESES_ELASTICSEARCH_TRANSPORT_PORT}
    environment:
      # mot de passe superadmin correspondant au login "elastic"
      - ELASTIC_PASSWORD=${THESES_ELASTICSEARCH_PASSWORD}
      # réglage explicites des ports internes et externes pour pouvoir fonctionner en cluster
      # cf https://blog.cri.epita.fr/post/2019-06-10-elasticsearch-cluster-formation-issue/
      - http.port=${THESES_ELASTICSEARCH_HTTP_PORT}
      - transport.port=${THESES_ELASTICSEARCH_TRANSPORT_PORT}
      - network.publish_host=${THESES_ELASTICSEARCH_CLUSTER_PUBLISH_HOST}
      # paramétrage du cluster elasticsearch
      - node.name=theses-es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}
      - node.roles=${THESES_ELASTICSEARCH_CLUSTER_NODE_ROLES}
      - cluster.name=${THESES_ELASTICSEARCH_CLUSTER_NAME}
      - cluster.initial_master_nodes=${THESES_ELASTICSEARCH_CLUSTER_INITIAL_MASTER_NODES}
      - discovery.seed_hosts=${THESES_ELASTICSEARCH_CLUSTER_DISCOVER_SEED_HOSTS}
      # pour désactiver les recherches complexe (conseillé par https://checkups.opster.com/checkup/result/75470)
      # "Recommendations : Allow expensive queries can be disabled by setting config search.allow_expensive_queries: false in the yaml config file and then restarting the node."
      - search.allow_expensive_queries=true
      # pour la quantité de données mises en cache
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#_cache_settings
      - indices.requests.cache.size=10%
      # réglage pour désactiver le swap: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_disable_swapping
      - bootstrap.memory_lock=true
      # pour éviter que les dump geoip soient téléchargés régulièrement dans /tmp/
      # cf https://abes-esr.atlassian.net/browse/THE-188
      # cf https://www.elastic.co/guide/en/elasticsearch/reference/current/geoip-processor.html#geoip-cluster-settings
      # cf https://www.elastic.co/guide/en/elasticsearch/reference/current/executable-jna-tmpdir.html
      - ingest.geoip.downloader.enabled=false
      - ES_TMPDIR=/usr/share/elasticsearch/tmp
      # paramètres de sécurité d'elasticsearch
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}.key
      - xpack.security.http.ssl.certificate=certs/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}.key
      - xpack.security.transport.ssl.certificate=certs/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}/es-${THESES_ELASTICSEARCH_CLUSTER_NODE_ID}.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      # licence à utiliser (basic ou trial pour un essai de 30 jours)
      - xpack.license.self_generated.type=basic
      # le port http pour le healthcheck d'elasticsearch
      - THESES_ELASTICSEARCH_HTTP_PORT=${THESES_ELASTICSEARCH_HTTP_PORT}
      # pour les sauvegardes (snapshots)
      - path.repo=${THESES_ELASTICSEARCH_SNAPSHOTS_DIR}
      # pour avoir plus ou moins de logs elasticsearch
      # DEBUG ou INFO (en prod mettre INFO)
      - logger.org.elasticsearch.discovery=INFO
    # réglage ulimits pour désactiver le swap: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_disable_swapping
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt -u elastic:${THESES_ELASTICSEARCH_PASSWORD} 'https://localhost:${THESES_ELASTICSEARCH_HTTP_PORT}/_cluster/health?timeout=5s&pretty=true' | grep status | grep -E -q '${THESES_ELASTICSEARCH_CLUSTER_HEALTHY_STATUS}'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=theses"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=elasticsearch"



# Cette configuration peut être décommentée pour pouvoir monter un cluster local elasticsearch
# elle permet de lancer plusieurs noeuds indépendants au niveau docker mais reliés par ce réseau commun
# pour lancer deux noeuds sur la même machine, il suffit alors de :
# 1) créer ce réseau via "docker network create theses-docker-es-cluster-network"
# 2) pour le noeud 2 utiliser la config suivante : https://github.com/abes-esr/theses-es-cluster-docker/
# 3) paramétrer le .env de chaque noeud avec THESES_ELASTICSEARCH_CLUSTER_NODE_ID qui vaut "01" ou "02" (fonction du noeud) :
#    THESES_ELASTICSEARCH_CLUSTER_NODE_ID=01
#    THESES_ELASTICSEARCH_CLUSTER_DISCOVER_SEED_HOSTS=theses-elasticsearch-co:10305,theses-elasticsearch-01:10305
#    THESES_ELASTICSEARCH_CLUSTER_INITIAL_MASTER_NODES=theses-es-01
# 4) lancer les deux noeuds dans leurs deux répertoires dédié avec "docker-compose up"
#networks:
#  default:
#    name: theses-docker-es-cluster-network
#    external: true

